### PR TITLE
[13.0][MIG] l10n_de_tax_statement

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Comment by llabusch93** [comment]
Any news here, why it does not get merged?

**Comment by astirpe** [comment]
2 reviews with approval are needed for being merged

**Comment by MrTango** [comment]
maybe @llabusch93 would make one review ;) it's a pity that work like this lays around for so long. I'll try to have a look at this too soon.

**Review by tbaden — APPROVED** [review]
did a code review: lgtm

**Review by tibor-barna — APPROVED** [review]
Code and function checked. No changes are necessary for me. LGTM. 
Thanks for your development efforts, @astirpe

**Comment by tbaden** [comment]
@OCA/local-germany-maintainers

**Pull request merged**
