### PR TITLE
[14.0][IMP] add international women's day as fixed holiday for berlin

### PR DESCRIPTION
**Pull request by yweng8111**

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I made a functional review.
It works fine. The 8th of March is now a public holiday in Berlin. :+1: 

@yweng8111 Can you check pre-commit?

**Comment by yweng8111** [comment]
The pre-commit error can be solved locally, if I changed the `.pre-commit-config.yaml"` But I'm not sure if I can also do this in this PR. Maybe the Maintainer should correct it.

```
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 6c30e90..44b9c48 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -15,7 +15,8 @@ default_language_version:
   node: "14.13.0"
 repos:
   - repo: https://github.com/psf/black
-    rev: 20.8b1
+    rev: 22.3.0
     hooks:
       - id: black
   - repo: https://github.com/prettier/pre-commit

**Comment by yweng8111** [comment]
The hook script of pre-commit want also change the files in module `l10n_de_tax_statement`. Should this also be done in other PR?

```
$ pre-commit run -a
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted l10n_de_tax_statement/migrations/13.0.1.0.0/post-migration.py
reformatted l10n_de_holidays/wizards/hr_holidays_public_generator_de.py
reformatted l10n_de_tax_statement/models/l10n_de_tax_statement.py

All done! ✨ 🍰 ✨
3 files reformatted, 30 files left unchanged.

prettier.................................................................Passed
prettier xml plugin......................................................Passed
eslint...............................................(no files to check)Skipped
- hook id: eslint
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Xml................................................................Passed
Mixed line ending........................................................Passed
flake8 except __init__.py................................................Passed
flake8 only __init__.py..................................................Passed
pylint with optional checks..............................................Passed
- hook id: pylint
- duration: 4.75s
pylint with mandatory checks.............................................Passed
pyupgrade................................................................Passed
isort except __init__.py.................................................Passed
Generate default setup.py for an addons directory........................Passed
```

**Comment by yweng8111** [comment]
@OCA/local-germany-maintainers 

Please check this PR.

**Review by chandni299 — APPROVED** [review]

**Comment by marylla** [comment]
@tv-openbig Hey hey, can you merge this too? :)

**Comment by pedrobaeza** [comment]
Please use ocabot merge command instead of merging directly.

**Comment by OSevangelist** [comment]
@pedrobaeza i'll take care of this no worries (in the future ;-)!

**Pull request merged**
