### PR TITLE
[15.0][MIG] l10n_de_holidays: Migration to 15.0

### PR DESCRIPTION
**Pull request by albig**

### CODE REVIEW

**Comment by albig** [comment]
Waiting for merge of https://github.com/OCA/l10n-germany/pull/116. This would fix two of the pylint errors.

**Comment by tv-openbig** [comment]
@albig 
I have done a functional check.
Left side is v15, right side v14.
The related state is missing after creation of public holidays.

Bildschirmfoto 2023-03-16 um 12 02 07

To get the full functionality of Odoo v14 it would be required to migrate the module l10n_de_country_states.
Hopefully we will receive a PR for that module too.

Nevertheless the module is working.
Therefore i will merge that.

Thanks for your patience and your direct reminder.

**Review by tv-openbig — APPROVED** [review]

**Comment by albig** [comment]
Thank you for your test and approval.

I'll fix the pre-commit failure and will provide a PR for `l10n_de_country_states`, too (I just wanted to progress step by step). Probably not today, all ;-)

**Comment by albig** [comment]
> @albig I have done a functional check. Left side is v15, right side v14. The related state is missing after creation of public holidays.

Thank you @tv-openbig for your test. I noticed to today, that German country states are part of Odoo 15.0 already (see https://github.com/odoo/odoo/commit/c741637fb9493e2d09f9299a6ff2aafddb852f7b). So we do not need the `l10n_de_country_states` module anymore.

The only change are the state codes. They are prefixed with `DE-` now. So `BW` get's `DE-BW`.

I changed the wizards of `l10n_de_holidays` accordingly.

Could you please check this and trigger the merge command again?

**Comment by tv-openbig** [comment]
I have reviewed the change. It is OK now. Thanks a lot, @albig 

Bildschirmfoto 2023-04-24 um 14 25 48

**Pull request merged**
