### PR TITLE
[14.0][mig]l10n_de_toponyms

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
Hello, it would be nice if someone review here.

**Comment by tv-openbig** [comment]
@hkapatel-initos

I get a rights issue, if i click "Import data from ..." in the wizard:
Bildschirmfoto 2021-09-09 um 11 40 35

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos
> 
> I get a rights issue, if i click "Import data from ..." in the wizard:
> Bildschirmfoto 2021-09-09 um 11 40 35

Hello, can you please recheck it?

**Comment by tv-openbig** [comment]
> > @hkapatel-initos
> > I get a rights issue, if i click "Import data from ..." in the wizard:
> > Bildschirmfoto 2021-09-09 um 11 40 35
> 
> Hello, can you please recheck it?

@hkapatel-initos

Ok, now it works as expected. I will merge the module as everything is green now. Thanks a lot for your qucik reply and efforts.
Bildschirmfoto 2021-09-14 um 15 23 28

**Pull request merged**
