### PR TITLE
[16.0][MIG] l10n_de_tax_statement_zm

### PR DESCRIPTION
**Pull request by MrGigSolutions**
Small changes to tests only.

Because this modules depends on l10n_de_tax_statement, this PR is based off the PR that migrates that module to 16.0: https://github.com/OCA/l10n-germany/pull/144

### CODE REVIEW

**Comment by MrGigSolutions** [comment]
retest

**Comment by MrGigSolutions** [comment]
I suspect the failing tests are because there are 4 demo invoices installed, these were not there in earlier versions. Think this should be corrected in datev_import_csv_dtvf.

**Comment by MrGigSolutions** [comment]
@ortlam,  would you mind having a look at this one?

**Comment by OSevangelist** [comment]
@ortlam would you mind to fix this ?

**Pull request closed without merging**
