### PR TITLE
[13.0][mig]l10n_de_skr03_mis_reports

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Comment by tv-openbig** [comment]
@hkapatel-initos

The functional test was successfull:
Bildschirmfoto 2021-09-15 um 08 58 13

**Comment by tv-openbig** [comment]
@hkapatel-initos 
In oca_dependencies.txt was mis_builder in line 3.
Shouldn't it be mis-builder ?

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos
> In oca_dependencies.txt was mis_builder in line 3.
> Shouldn't it be mis-builder ?

Travis is failed https://app.travis-ci.com/github/OCA/l10n-germany/jobs/537992884#L880

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig now you can merge it.

**Comment by tv-openbig** [comment]
@hkapatel-initos Do we really need the dependency to l10n_generic_coa ?

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos Do we really need the dependency to l10n_generic_coa?

I removed the l10n_generic_coa dependency from a manifest  and  add it in (https://github.com/OCA/l10n-germany/pull/92/commits/9e037769d438202d4aeae889512a6490b5ab2113#diff-95557d53bf91069e59d82b9d8fcfaf52ec84a762858983edd5ef3c9b3e4c8191R19) 
To make Travis happy.

**Pull request merged**
