### PR TITLE
[14.0] [mig] l10n_de_holidays

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM. Done code review and functional tests.

**Comment by fshah-initos** [comment]
It would be ncie if we get the reviews here

**Comment by fshah-initos** [comment]
Hi @tbaden I will be nice if you can review the PR

**Review by tbaden — APPROVED** [review]

**Comment by fshah-initos** [comment]
It will be nice if maintainers merge this PR

**Comment by fshah-initos** [comment]
Can we merge this PR? hence approved

**Comment by tbaden** [comment]
@OCA/local-germany-maintainers

**Pull request merged**
