### PR TITLE
add OCA author

### PR DESCRIPTION
**Pull request by ntodorova**
Add OCA as author.

### CODE REVIEW

**Comment by yvaucher** [comment]
@ntodorova Thanks, however you need to put it in the same string, apps.odoo.com doesn't support list but split on coma.

**Comment by OSguard** [comment]
a other way is:

```
    'Odoo Community Association (OCA),'
    'initOS GmbH & Co. KG',
```

that looks clear and works well

**Comment by OSguard** [comment]
@yvaucher now the space after the comma is not needed or?

**Comment by hbrunn** [comment]
@OSguard you need the comma, but no space

**Comment by OSguard** [comment]
sorry

```
    'Odoo Community Association (OCA),'
    'initOS GmbH & Co. KG',
```

is what i was looking for

**Comment by yvaucher** [comment]
:+1:  either for current state or the one proposed by @OSguard

**Comment by OSguard** [comment]
:+1:

**Comment by dreispt** [comment]
:+1:

**Pull request merged**
