### PR TITLE
[13.0][mig]l10n_de_country_states

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
it would be nice if someone help me to resolve This issue.

**Comment by tv-openbig** [comment]
@hkapatel-initos

I have reviewed the installation and functions of the module:
Bildschirmfoto 2021-09-09 um 11 59 22

Is it possible to merge even if the travis check failed ?

**Comment by kmatthes** [comment]
@tv-openbig Maybe I missed it, but why do you want to merge with failed travis checks?

**Comment by tv-openbig** [comment]
> @tv-openbig Maybe I missed it, but why do you want to merge with failed travis checks?

@kmatthes That's correct. I have removed the "ready to merge" label. From functional side, the module is working on a local installation.

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig all the checks are passed can we merge this?

**Pull request merged**
