### PR TITLE
[wip][14.0][mig]l10n_de_tax_statement_zm

### PR DESCRIPTION
**Pull request by hkapatel-initos**
Dependencies
l10n_de_tax_statement  #80

### CODE REVIEW

**Comment by tv-openbig** [comment]
@hkapatel-initos Hello, if i have installed the module l10n_de_tax_statement it is possible to click on "post" to move the state of the statement from draft -> posted:
Bildschirmfoto 2021-09-08 um 15 10 26

If i install on top this module i get an "Odoo Server Error":
Bildschirmfoto 2021-09-08 um 15 11 33

Here is the detailed log:
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 172, in post
    self._check_config_tag_41()
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 100, in _check_config_tag_41
    if not statement.tag_41_base:
  File "/odoo/odoo-server/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo-server/odoo/models.py", line 4063, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 29, in _compute_tag_41
    config = self.env["l10n.de.tax.statement.config"].search(
  File "/odoo/odoo-server/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/odoo/odoo-server/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'l10n.de.tax.statement.config'

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig I resolve the issue can you please re-check it?
and Travis is failed because of the dependent module.

**Comment by tv-openbig** [comment]
> Hello, @tv-openbig I resolve the issue can you please re-check it? and Travis is failed because of the dependent module.

Hello @hkapatel-initos The issue is still the same:
Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 172, in post
    self._check_config_tag_41()
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 100, in _check_config_tag_41
    if not statement.tag_41_base:
  File "/odoo/odoo-server/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo-server/odoo/models.py", line 4063, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 29, in _compute_tag_41
    config = self.env["l10n.de.tax.statement.config"].search(
  File "/odoo/odoo-server/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/odoo/odoo-server/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'l10n.de.tax.statement.config'

**Comment by hkapatel-initos** [comment]
> > Hello, @tv-openbig I resolve the issue can you please re-check it? and Travis is failed because of the dependent module.
> 
> Hello @hkapatel-initos The issue is still the same: Odoo Server Error Traceback (most recent call last): File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch result = request.dispatch() File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch result = self._call_function(**self.params) File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function return checked_call(self.db, *args, **kwargs) File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper return f(dbname, *args, **kwargs) File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call result = self.endpoint(*a, **kw) File "/odoo/odoo-server/odoo/http.py", line 913, in **call** return self.method(*args, **kw) File "/odoo/odoo-server/odoo/http.py", line 532, in response_wrap response = f(*args, **kw) File "/odoo/odoo-server/addons/web/controllers/main.py", line 1393, in call_button action = self._call_kw(model, method, args, kwargs) File "/odoo/odoo-server/addons/web/controllers/main.py", line 1381, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/odoo/odoo-server/odoo/api.py", line 396, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/odoo/odoo-server/odoo/api.py", line 383, in _call_kw_multi result = method(recs, *args, **kwargs) File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 172, in post self._check_config_tag_41() File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 100, in _check_config_tag_41 if not statement.tag_41_base: File "/odoo/odoo-server/odoo/fields.py", line 2483, in **get** return super().**get**(records, owner) File "/odoo/odoo-server/odoo/fields.py", line 1019, in **get** self.compute_value(recs) File "/odoo/odoo-server/odoo/fields.py", line 1175, in compute_value records._compute_field_value(self) File "/odoo/odoo-server/odoo/models.py", line 4063, in _compute_field_value getattr(self, field.compute)() File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 29, in _compute_tag_41 config = self.env["l10n.de.tax.statement.config"].search( File "/odoo/odoo-server/odoo/api.py", line 473, in **getitem** return self.registry[model_name]._browse(self, (), ()) File "/odoo/odoo-server/odoo/modules/registry.py", line 177, in **getitem** return self.models[model_name] Exception
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/odoo/odoo-server/odoo/http.py", line 316, in _handle_exception raise exception.with_traceback(None) from new_cause KeyError: 'l10n.de.tax.statement.config'

sorry it was my mistake I have done changes in the dependent module, it would be nice if you please functional test again.

**Comment by tv-openbig** [comment]
> > > Hello, @tv-openbig I resolve the issue can you please re-check it? and Travis is failed because of the dependent module.
> > 
> > 
> > Hello @hkapatel-initos The issue is still the same: Odoo Server Error Traceback (most recent call last): File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch result = request.dispatch() File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch result = self._call_function(**self.params) File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function return checked_call(self.db, *args, **kwargs) File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper return f(dbname, *args, **kwargs) File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call result = self.endpoint(*a, **kw) File "/odoo/odoo-server/odoo/http.py", line 913, in **call** return self.method(*args, **kw) File "/odoo/odoo-server/odoo/http.py", line 532, in response_wrap response = f(*args, **kw) File "/odoo/odoo-server/addons/web/controllers/main.py", line 1393, in call_button action = self._call_kw(model, method, args, kwargs) File "/odoo/odoo-server/addons/web/controllers/main.py", line 1381, in _call_kw return call_kw(request.env[model], method, args, kwargs) File "/odoo/odoo-server/odoo/api.py", line 396, in call_kw result = _call_kw_multi(method, model, args, kwargs) File "/odoo/odoo-server/odoo/api.py", line 383, in _call_kw_multi result = method(recs, *args, **kwargs) File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 172, in post self._check_config_tag_41() File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 100, in _check_config_tag_41 if not statement.tag_41_base: File "/odoo/odoo-server/odoo/fields.py", line 2483, in **get** return super().**get**(records, owner) File "/odoo/odoo-server/odoo/fields.py", line 1019, in **get** self.compute_value(recs) File "/odoo/odoo-server/odoo/fields.py", line 1175, in compute_value records._compute_field_value(self) File "/odoo/odoo-server/odoo/models.py", line 4063, in _compute_field_value getattr(self, field.compute)() File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 29, in _compute_tag_41 config = self.env["l10n.de.tax.statement.config"].search( File "/odoo/odoo-server/odoo/api.py", line 473, in **getitem** return self.registry[model_name]._browse(self, (), ()) File "/odoo/odoo-server/odoo/modules/registry.py", line 177, in **getitem** return self.models[model_name] Exception
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last): File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/odoo/odoo-server/odoo/http.py", line 316, in _handle_exception raise exception.with_traceback(None) from new_cause KeyError: 'l10n.de.tax.statement.config'
> 
> sorry it was my mistake I have done changes in the dependent module, it would be nice if you please functional test again.

Hello @hkapatel-initos ,
the error is unfortunately still the same:

Odoo Server Error
Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 172, in post
    self._check_config_tag_41()
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 100, in _check_config_tag_41
    if not statement.tag_41_base:
  File "/odoo/odoo-server/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/odoo/odoo-server/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/odoo/odoo-server/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/odoo/odoo-server/odoo/models.py", line 4063, in _compute_field_value
    getattr(self, field.compute)()
  File "/odoo/odoo-server/addons/l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py", line 29, in _compute_tag_41
    config = self.env["l10n.de.tax.statement.config"].search(
  File "/odoo/odoo-server/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
  File "/odoo/odoo-server/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
KeyError: 'l10n.de.tax.statement.config'

**Comment by dsolanki-initos** [comment]
@tv-openbig @hkapatel-initos is not available I would like to takeover this PR I  resolve the key error but after v12  odoo changed the tags from 'account.account.tag' and in odoo14   l10n_de.tag_tax_41 this  tag is not available  in account.account.tag object  so we don't get the zm liens in this module so we get error tag 41is not configured for this company.

**Comment by tv-openbig** [comment]
Hello @dsolanki-initos ,

i assume it was changed to l10n_de.tax_report_de_tag_41
or to:
l10n_de.tag_de_intracom_community_delivery

In fact there is an issue with that tax in Odoo core. Odoo changed so many things with the tax grid without properly requested reviews. What you can see is that they assigned two tax tags. Currently i am not sure which one to use. I assume the second one. And in fact it might also caused the issue with the l10n_de_tax_statement related modules migration (no invoice in the list)...


Bildschirmfoto 2021-11-12 um 18 03 19



> @tv-openbig @hkapatel-initos is not available I would like to takeover this PR I resolve the key error but after v12 odoo changed the tags from 'account.account.tag' and in odoo14 l10n_de.tag_tax_41 this tag is not available in account.account.tag object so we don't get the zm liens in this module so we get error tag 41is not configured for this company.

Could you check that ?

**Comment by dsolanki-initos** [comment]
I have checked the tages in odoo14 according to your suggestion In account_account_tags_data file some tages are no longer available in the v14 odoo base 
like tag_77_base, tag_76_base, tag_89_base,
This tag is defined in the account.tax.report.line object and I try to add l10n_de.tax_report_de_tag_41 
from the account.tax.report.line object but I didn't get the correct value.
Will you please suggest to us which tags will be suitable for german accounting and for which one we should proceed?

**Comment by dsolanki-initos** [comment]
Hi @tv-openbig 
I have checked the tages in odoo14 according to your suggestion In account_account_tags_data file some tages are no longer available in the v14 odoo base
like ex: (tag_77_base, tag_76_base, tag_89_base,)
l10n_de.tax_report_de_tag_41 tag is defined in the account.tax.report.line object and I try to add from the account.tax.report.line object but I didn't get the correct value.
Will you please suggest to us which tags will be suitable for german accounting and for which one we should proceed?

**Comment by ortlam** [comment]
#80 should be ready soon, then this PR can progress.

**Comment by OSevangelist** [comment]
What is the status here @ortlam can somebody like @mathiasfrancke for instance maybe do a review and can we together get the CI green ?

**Comment by ortlam** [comment]
@tv-openbig @OSevangelist I finished the PR, the unit tests are fixed and I think it is ready to be merged. Can you take a look, please?

**Comment by OSevangelist** [comment]
@tv-openbig @ortlam fyi, i have merged this now as the only missing part was the CI to be fixed and all green

**Pull request merged**
