### PR TITLE
[12.0][mig]l10n_de_tax_statement_zm

### PR DESCRIPTION
**Pull request by hkapatel-initos**
migrate  zm export functionality in this pull
Go to the zm page and just click on the download button to get a valid CSV file for Elster online

https://github.com/OCA/l10n-germany/pull/70

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig Can you please check this pull and Travis is failed because of the dependent module
https://app.travis-ci.com/github/OCA/l10n-germany/jobs/540164511#L335.

**Comment by hkapatel-initos** [comment]
Hi, @tv-openbig  it would be great if you test this module and Travis is happy so we can merge it ASPS.

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig and @Guenzn I have migrated zm export functionality in this pull  #70 it would be great if you could check this functionality in this module. 

And Travis is failed because of  (l10n_de_toponyms) another Module
https://app.travis-ci.com/github/OCA/l10n-germany/jobs/542147988#L335

**Comment by tv-openbig** [comment]
> Hello, @tv-openbig and @Guenzn I have migrated zm export functionality in this pull #70 it would be great if you could check this functionality in this module.
> 
> And Travis is failed because of (l10n_de_toponyms) another Module https://app.travis-ci.com/github/OCA/l10n-germany/jobs/542147988#L335

Hello @hkapatel-initos ,
i have checked the new integrated export functionality:
Bildschirmfoto 2021-10-08 um 15 18 15
It works as expected. Nevertheless i would like to point to a potential improvement: the name of the Downloaded file is currently "Download" without any specification of file name  and file extension. It would be better if file name would be the same as the filed "name" of the report (here in the example: "big-consulting GmbH: 2021-01-01 2021-01-31" converted to "big-consultingGmbH_2021-01-01 2021-01-31" by removal of blanks and replacement of ":" by "_" plus the file extension ".csv".


Furthermore we should update the readme with this additional feature as it replaces the described manual way of uploading / editing the advanced german vat declaration.

The module you mentionded as a missing dependency seems to be there in this repository of V12 modules. I currently see those remaining issues in the dependent l10n_de_toponyms module:
************* Module l10n_de_toponyms
l10n_de_toponyms/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module l10n_de_toponyms.wizard.__init__
l10n_de_toponyms/wizard/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module l10n_de_toponyms.tests.__init__
l10n_de_toponyms/tests/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary

 ... and those ones in this module:
l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py:175:5: E303 too many blank lines (2)
l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py:258:9: F841 local variable 'zm_download_lines' is assigned to but never used
l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py:268:10: W292 no newline at end of file
l10n_de_tax_statement_zm/tests/test_l10n_de_tax_statement_zm.py:202:33: W292 no newline at end of file


Nevertheless i am not sure if it makes sense to bypass the travis check results.

**Review by dsolanki-initos — COMMENTED** [review]
Code review and functional test LGTM
Can you fix this in another PR? https://app.travis-ci.com/github/OCA/l10n-germany/jobs/542147988#L335

**Comment by hkapatel-initos** [comment]
> > Hello, @tv-openbig and @Guenzn I have migrated zm export functionality in this pull #70 it would be great if you could check this functionality in this module.
> > And Travis is failed because of (l10n_de_toponyms) another Module https://app.travis-ci.com/github/OCA/l10n-germany/jobs/542147988#L335
> 
> Hello @hkapatel-initos , i have checked the new integrated export functionality: Bildschirmfoto 2021-10-08 um 15 18 15 It works as expected. Nevertheless i would like to point to a potential improvement: the name of the Downloaded file is currently "Download" without any specification of file name and file extension. It would be better if file name would be the same as the filed "name" of the report (here in the example: "big-consulting GmbH: 2021-01-01 2021-01-31" converted to "big-consultingGmbH_2021-01-01 2021-01-31" by removal of blanks and replacement of ":" by "_" plus the file extension ".csv".
> 
> Furthermore we should update the readme with this additional feature as it replaces the described manual way of uploading / editing the advanced german vat declaration.
> 
> The module you mentionded as a missing dependency seems to be there in this repository of V12 modules. I currently see those remaining issues in the dependent l10n_de_toponyms module: ************* Module l10n_de_toponyms l10n_de_toponyms/**init**.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary ************* Module l10n_de_toponyms.wizard.**init** l10n_de_toponyms/wizard/**init**.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary ************* Module l10n_de_toponyms.tests.**init** l10n_de_toponyms/tests/**init**.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
> 
> ... and those ones in this module: l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py:175:5: E303 too many blank lines (2) l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py:258:9: F841 local variable 'zm_download_lines' is assigned to but never used l10n_de_tax_statement_zm/models/l10n_de_tax_statement.py:268:10: W292 no newline at end of file l10n_de_tax_statement_zm/tests/test_l10n_de_tax_statement_zm.py:202:33: W292 no newline at end of file
> 
> Nevertheless i am not sure if it makes sense to bypass the travis check results.

hello, @tv-openbig changes are done can you please re-check again.

**Comment by tv-openbig** [comment]
Hello,

@hkapatel-initos , i have checked the improvement (see bottom of screenshot). It works as expected.

Bildschirmfoto 2021-10-26 um 10 39 16

**Comment by tv-openbig** [comment]
Hello @hkapatel-initos ,

may you also update some text:


README.rst
=========

1.) search (in README.rst):
* If you want to transmit the values to the official report form, f.e. by "www.elster.de" you would have to enter two lines if both columns product + services contains values.

replace it by:
* If you want to transmit the values to the official report form, f.e. by "www.elster.de" you would have to go to the second tab of odoo’s tax statement form where you can see all the lines you would have to declare to the german tax authorities for the selected period. If you click on „Download.CSV“ you will get the file you may upload on the 2nd side of the declaration form „Zusammenfassende Meldung“ on the official tax declaration portal „www.elster.de“. As another option you may enter the valaues by hand, however you would have to enter two lines if both columns product + services on the tab „Zusammenfassende Meldung“ contains values.

INSTALL.rst
=========

1.) search (in /readme/INSTALL.rst):
To install this module, you need to:
1. Install module l10n_de_tax_statement version >= 11.0.1.0.0.

replace it by:
To install this module, you need to:
1. Install module l10n_de_tax_statement version >= 12.0.1.0.0.

USAGE.rst
=========

1.) search (in /readme/USAGE.rst):

5. If you want to transmit the values to the official report form, f.e. by "www.elster.de" you would have to enter two lines if both columns product + services contains values.

replace it by:
5. If you want to transmit the values to the official report form, f.e. by "www.elster.de" you would have to go to the second tab of odoo’s tax statement form where you can see all the lines you would have to declare to the german tax authorities for the selected period. If you click on „Download.CSV“ you will get the file you may upload on the 2nd side of the declaration form „Zusammenfassende Meldung“ on the official tax declaration portal „www.elster.de“. As another option you may enter the valaues by hand, however you would have to enter two lines if both columns product + services on the tab „Zusammenfassende Meldung“ contains values.

ROADMAP.rst
==========

1.) search (in /readme/ROADMAP.rst):
* Calculate separated lines for product and service sales. Currently the values are in two columns per intra-community partner.

replace it by:
* Calculate separated lines for product and service sales. Currently the values are in two columns per intra-community partner. You want have any issues if you declare the „Zusammenfassende Meldung“ report by upload of the .csv file you may download. Therefore you would have to go to the second tab of odoo’s tax statement form where you can see all the lines you would have to declare to the german tax authorities for the selected period. If you click on „Download.CSV“ you will get the file you may upload on the 2nd side of the declaration form „Zusammenfassende Meldung“ on the official tax declaration portal „www.elster.de“.


DESCRIPTION.rst
=============
1.) search (in /readme/DESCRIPTION.rst):
* If you want to transmit the values to the official report form, f.e. by "www.elster.de" you would have to enter two lines if both columns product + services contains values.

replace it by:
* If you want to transmit the values to the official report form, f.e. by "www.elster.de" you would have to go to the second tab of odoo’s tax statement form where you can see all the lines you would have to declare to the german tax authorities for the selected period. If you click on „Download.CSV“ you will get the file you may upload on the 2nd side of the declaration form „Zusammenfassende Meldung“ on the official tax declaration portal „www.elster.de“. As another option you may enter the valaues by hand, however you would have to enter two lines if both columns product + services on the tab „Zusammenfassende Meldung“ contains values.

**Review by dsolanki-initos — APPROVED** [review]
Code review and functional test LGTM
<br class="Apple-interchange-newline">

**Comment by hkapatel-initos** [comment]
@tv-openbig Can we merge?

**Comment by tv-openbig** [comment]
@hkapatel-initos I am merging now. 
The issue here https://github.com/OCA/l10n-germany/pull/83 unfortunately still persists.
I assume it is related to this issue in the dependent "father" module:
https://github.com/OCA/l10n-germany/pull/80

**Pull request merged**
