### PR TITLE
[MIG][16.0] Migration of datev_export_xml

### PR DESCRIPTION
**Pull request by jsierp**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by OSevangelist** [comment]
@fkantelberg can you fix that as well ?

**Comment by fkantelberg** [comment]
I mean I can superseed the PR but I can't push to the source repository nor do I want to claim the migration work

**Comment by tv-openbig** [comment]
@jsierp Hello Jan, i have just merged the following PR (V15):
https://github.com/OCA/l10n-germany/pull/126

I hope that helps to prevent the commit history.
@hbrunn Is a new PR required ?

**Comment by hbrunn** [comment]
no, if @jsierp does the above and force pushes, this one will be good to merge. Or if you're in a hurry and Jan doesn't have time to get back to this, I think it's okay to say

```sh
git checkout origin/16.0 -b 16.0-mig-datev_export_xml
git format-patch --keep-subject --stdout origin/16.0..origin/15.0 -- datev_export datev_export_xml | git am -3 --keep --ignore-whitespace
git remote add solvti https://github.com/solvti/l10n-germany
git fetch solvti
git cherry-pick 7e02524 -X theirs
git cherry-pick bb472b8
```

then you end up with a branch that is the same code as this one, but has history and important, you keep the attribution.

Not super polite, but also not super insulting in my book.

**Comment by OSevangelist** [comment]
@jsierp @akselnooit would you mind to get this right, otherwise we gonna close this and create a new PR with the preserved history but this would be somewhat highjacking your contribution we would be glad if you fix it yourself. Thanks a lot in advance. Cheers fyi @tv-openbig

**Comment by jsierp** [comment]
Hello, I have created a new PR: https://github.com/OCA/l10n-germany/pull/153 does the git history look correct now?

**Pull request closed without merging**
