### PR TITLE
[14.0][mig]l10n_de_skr04_mis_reports

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
it would be great if someone reviews it.

**Review by hkapatel-initos — APPROVED** [review]
LGTM

**Comment by hkapatel-initos** [comment]
Hello, it would be nice if someone reviews here.

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig it would be nice if you review this Pull.

**Review by tv-openbig — APPROVED** [review]

**Pull request merged**
