### PR TITLE
[14.0] [mig] l10n_de_location_nuts

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
No major change. LGTM.
Code review and Functional Tests.

**Comment by fshah-initos** [comment]
@tbaden  It would be great if you could add reviews here.

**Review by tbaden — APPROVED** [review]
code review: LGTM

**Comment by fshah-initos** [comment]
Hi @tbaden it would be great if you could merge the PR, hence it is approved.

**Comment by fshah-initos** [comment]
It would be nice if we could merge the PR.

**Comment by tbaden** [comment]
I have no power here

**Comment by fshah-initos** [comment]
It would be nice if we could merge the PR.

**Comment by fshah-initos** [comment]
It seems PR has approved label from so many days. It would be great if the maintainers could merge it.

**Comment by tbaden** [comment]
@OCA/local-germany-maintainers

**Pull request merged**
