### PR TITLE
[14.0][FIX][IMP]: l10n_de_holidays: add World Children's Day (TH), fix Repentance Day (SN)

### PR DESCRIPTION
**Pull request by albig**
Backport of https://github.com/OCA/l10n-germany/pull/124

### CODE REVIEW

**Comment by marylla** [comment]
@albig Do you know why the runboat is still pending? Can you trigger building it somehow? Same for the Fix PR for version 15. I'd like to do functional testing und help merging this one.

**Comment by albig** [comment]
Thank you for looking into this. I'm currently on vacation and cannot contribute. Next week, I'm back.

If I remember right, the pending state in the 14.0 branch is due to not sufficient test coverage. In 15.0 the same code is ok. If you know how to fix this, help would be great.

Am 20. Juli 2023 09:36:01 MESZ schrieb Maria Sparenberg ***@***.***>:
>@albig Do you know why the runboat is still pending? Can you trigger building it somehow? Same for the Fix PR for version 15. I'd like to do functional testing und help merging this one.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/OCA/l10n-germany/pull/125#issuecomment-1643427461
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- Von /e/ Mail gesendet.

**Comment by albig** [comment]
Dear @marylla , I assume, there was some failure on the runboat service. Now I've triggered all checks again by force push (there was no "restart" or similar) and now runboat just did its job.

All runboats for this repository may be found here:

https://runboat.odoo-community.org/webui/builds.html?repo=oca/l10n-germany

Looking forward to your testing results.

**Comment by tv-openbig** [comment]
I have checked this.
Bildschirmfoto 2023-09-03 um 15 16 31

**Pull request merged**
