### PR TITLE
[13.0][IMP] add international women's day as fixed holiday for berlin

### PR DESCRIPTION
**Pull request by yweng8111**

### CODE REVIEW

**Review by marylla — APPROVED** [review]
I made a functional review.
It works fine. The 8th of March is now a public holiday in Berlin. :+1: 

@yweng8111 But can you check pre-commit, unit test and travis. It's failing.

**Comment by yweng8111** [comment]
The pre-commit error of black can be solved locally, as I changed the `.pre-commit-config.yaml`. But I'm not sure if I can also do this in this PR. Maybe the Maintainer should correct it. And the other error `AttributeError: module 'collections' has no attribute 'MutableSet'` doesn't occur locally for me.

```
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index 6c30e90..44b9c48 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -15,7 +15,8 @@ default_language_version:
   node: "14.13.0"
 repos:
   - repo: https://github.com/psf/black
-    rev: 19.10b0
+    rev: 22.3.0
     hooks:
       - id: black
   - repo: https://github.com/prettier/pre-commit
```

**Comment by yweng8111** [comment]
The hook script of pre-commit want also change the files in module `l10n_de_tax_statement`. Should this also be done in other PR?

```
$ pre-commit run -a
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted l10n_de_tax_statement/migrations/13.0.1.0.0/post-migration.py
reformatted l10n_de_holidays/wizards/hr_holidays_public_generator_de.py
reformatted l10n_de_tax_statement/models/l10n_de_tax_statement.py

All done! ✨ 🍰 ✨
3 files reformatted, 30 files left unchanged.

prettier.................................................................Passed
prettier xml plugin......................................................Passed
eslint...............................................(no files to check)Skipped
- hook id: eslint
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Debug Statements (Python)................................................Passed
Fix python encoding pragma...............................................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Check for merge conflicts................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check Xml................................................................Passed
Mixed line ending........................................................Passed
flake8 except __init__.py................................................Passed
flake8 only __init__.py..................................................Passed
pylint with optional checks..............................................Passed
- hook id: pylint
- duration: 4.75s
pylint with mandatory checks.............................................Passed
pyupgrade................................................................Passed
isort except __init__.py.................................................Passed
Generate default setup.py for an addons directory........................Passed
```

**Comment by yweng8111** [comment]
@OCA/local-germany-maintainers 

Please check this pre-commit

**Comment by yweng8111** [comment]
I also don't know how to fix this error from Unit Test.
Module base_country_state_translatable is in the oca/partner-contact Repo, which was already added into the [oca_dependencies.txt](https://github.com/OCA/l10n-germany/blob/13.0/oca_dependencies.txt). Can someone help me?

```
 odoo.exceptions.UserError: ("You try to install module 'l10n_de_country_states' that depends on module 'base_country_state_translatable'.\nBut the latter module is not available in your system.", '')
 ```

**Comment by hbrunn** [comment]
@yweng8111 the CI definition of this branch is very outdated and also contains deprecated workflows, I updated this in https://github.com/OCA/l10n-germany/pull/112 - so we should try to get this merged, then you can rebase and all should be fine

**Pull request closed without merging**
