### PR TITLE
[14.0] [mig] l10n_de_skr03_mis_reports

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
It would be great if you could add the reviews here

**Comment by hkapatel-initos** [comment]
It would be nice if someone reviews it.

**Review by hkapatel-initos — APPROVED** [review]
code review LGTM

**Comment by hkapatel-initos** [comment]
Hello, @marylla it would be nice if you add a review here.

**Comment by tv-openbig** [comment]
@hkapatel-initos
I have successfully installed and configured a german profit & loss report on a local test system with some example data.
Bildschirmfoto 2021-09-08 um 14 31 20

I assume i can merge this PR !

**Comment by tv-openbig** [comment]
@hkapatel-initos 
Is someting else required to merge ?

**Review by tv-openbig — APPROVED** [review]

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos
> Is someting else required to merge ?

NO, it is completed from my side.

**Pull request merged**
