### PR TITLE
[ADD] l10n_de_zip : zip codes for germany

### PR DESCRIPTION
**Pull request by vrenaville**

### CODE REVIEW

**Comment by rafaelbn** [comment]
@vrenaville we are from Spain and we have alredy done, @antespi where?

Runbot and travis are failing, please check

**Comment by vrenaville** [comment]
@rafaelbn Sorry for the delay, I completely forget this PR

could you please give the link to the PR or the module

**Comment by rafaelbn** [comment]
Check
- https://github.com/OCA/partner-contact/tree/8.0/base_location_geonames_import
- https://github.com/OCA/partner-contact/tree/8.0/base_location_nuts
- https://github.com/OCA/l10n-germany/pull/11

cc @antespi @pedrobaeza

**Comment by vrenaville** [comment]
@rafaelbn , thanks for the links.

My PR is for V7, If someone plan to migrate it to V8, he can change to fit requirement of base_location_nuts.

What do you think about that.

**Comment by rafaelbn** [comment]
OK

**Comment by pedrobaeza** [comment]
This is very old, so I close it.

**Pull request closed without merging**
