### PR TITLE
[16.0][MIG] l10n_de_location_nuts

### PR DESCRIPTION
**Pull request by edlopen**
Standard migration of l10n_de_location_nuts.

@moduon MT-1797

@yajo @EmilioPascual @Shide @fcvalgar @rafaelbn review this PR when you can. Thank you!

I've removed the l10n_de_country_states dependency as in 16.0 Odoo includes Germany states.

### CODE REVIEW

**Review by EmilioPascual — APPROVED** [review]
Nice job @edlopen.
Functional and code review.

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM Thank you @edlopen

**Review by yajo — APPROVED** [review]

**Comment by EmilioPascual** [comment]
@tv-openbig can you review and merge if it's ok, please?
Thank you.

**Review by Shide — APPROVED** [review]

**Review by yajo — APPROVED** [review]

**Comment by tv-openbig** [comment]
@pedrobaeza @EmilioPascual I have also done a functional review. Can we skip / ignore the codecov gap ? I assume it have to be fixed in advance of a merge or am i wrong ?

**Comment by pedrobaeza** [comment]
Yes, don't worry. Codecov check is optional and doesn't block the merges, and I also see that sometimes is not reporting a proper value, giving false positives or negatives.

**Pull request merged**
