### PR TITLE
[12.0][MIG] l10n_de_holidays

### PR DESCRIPTION
**Pull request by abdounasser202**
Migration of `l10n_de_holidays`

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by abdounasser202** [comment]
Could you please tell me why runbot build is failing ?

**Comment by manengel** [comment]
@abdounasser202 Are there any news in regard of this? At least from my side, Github reports that all checks (including the runbot) are okay so far.

**Comment by abdounasser202** [comment]
@manengel all is fine on my side

**Review by tbaden — APPROVED** [review]
did a code review: lgtm

**Review by hkapatel-initos — APPROVED** [review]
LGTM

**Pull request merged**
