### PR TITLE
[13.0][mig]l10n_de_skr04_mis_reports

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
Hello, @astirpe it would be nice if could you suggest to me how to resolve this Travis issue.
https://app.travis-ci.com/github/OCA/l10n-germany/jobs/536120059#L302

**Comment by nilshamerlinck** [comment]
Hi @hkapatel-initos travis failing was due to https://github.com/OCA/maintainer-quality-tools/pull/695
I've just restarted the 2 failed jobs, should be ok now: https://app.travis-ci.com/github/OCA/l10n-germany/builds/237161408

**Comment by tv-openbig** [comment]
@hkapatel-initos 
I did a functional check on a V13 setup:
Bildschirmfoto 2021-09-09 um 12 45 23

May i merge, even if the travis check fails ?

**Comment by astirpe** [comment]
@hkapatel-initos To fix the travis error, add `mis-builder` branch in `oca_dependencies.txt`, like it's done in V12: https://github.com/OCA/l10n-germany/blob/12.0/oca_dependencies.txt#L3

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos To fix the travis error, add `mis-builder` branch in `oca_dependencies.txt`, like it's done in V12: https://github.com/OCA/l10n-germany/blob/12.0/oca_dependencies.txt#L3

I have already add it
https://github.com/initOS/l10n-germany/commit/82b8d381d4e9ba53db59571dc6294b8480f1868e#diff-26ad8371210e2d99f802396dff300a8931802487380c06c04ec5b501b33a186bR4

**Comment by hkapatel-initos** [comment]
Hello, Travis is happy @tv-openbig it would be nice if you try to merge it.

**Pull request merged**
