### PR TITLE
Separated Lint tests

### PR DESCRIPTION
**Pull request by yvaucher**

### CODE REVIEW

**Comment by OSguard** [comment]
- travis_run_flake8 is also depreciated or?

**Comment by yvaucher** [comment]
@OSguard Thanks, I just fixed it.

**Comment by OSguard** [comment]
:+1:

After merging this, i should also fix the 7.0 branch the same way, right?

**Comment by yvaucher** [comment]
@OSguard If you want to separate it on 7.0 you can use those sed commands:

```
sed -i '/VERSION=/ s/$/ LINT_CHECK="0"/' .travis.yml
sed -i '/^env:$/a\ \ - VERSION="7.0" LINT_CHECK="1"' .travis.yml
```

**Comment by lepistone** [comment]
:+1:

**Comment by guewen** [comment]
:+1:

**Comment by guewen** [comment]
oh I can't merge this one

**Comment by OSguard** [comment]
But i can :) thx for review

**Pull request merged**
