### PR TITLE
 MIG l10n_de_steuernummer

### PR DESCRIPTION
**Pull request by rami-wafaie**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please follow migration guide: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

**Comment by OSevangelist** [comment]
Hi @pedrobaeza thanks for the hint !
@rami-wafaie could you please take care of this and do a small technical summary thenafter for out team to share the migration hurdles and key learnings. thx in advance

**Comment by pedrobaeza** [comment]
Tell me any doubt you have

**Comment by OSevangelist** [comment]
I don't think there is something wrong with it, we just have to follow your link and hopefully it'll work. I just want to make sure that the knowledge about that is thenafter shared internally at INITOS and with the community (if anything should be missing in the document)

**Comment by pedrobaeza** [comment]
OK, good

**Comment by pedrobaeza** [comment]
I'm still seeing that the migration guide hasn't been followed for preserving commit history. Please do it.

**Comment by OSevangelist** [comment]
@rami could you please do that asap. Thx

Am Donnerstag, den 01.02.2018, 17:06 +0000 schrieb Pedro M. Baeza:
> I'm still seeing that the migration guide hasn't been followed for preserving commit history. Please do it.
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Dr.-Ing. Frederik Kramer
Geschäftsführer
        
initOS GmbH
An der Eisenbahn 1
21224 Rosengarten
        
Phone:  +49 4105 56156-12
Fax:    +49 4105 56156-10
Mobil:  +49 179 3901819
        
Email: frederik.kramer@initos.com
Web:   www.initos.com
        
Geschäftsführung:
Dr.-Ing. Frederik Kramer & Dipl.-Ing. (FH) Torsten Francke

Sitz der Gesellschaft: Rosengarten – Klecken
Amtsgericht Tostedt, HRB 205226
Steuer-Nr: 15/200/53247
USt-IdNr.: DE815580155

**Comment by rami-wafaie** [comment]
@pedrobaeza  The origin branch was cloaned from our github rebo (not the OCA) that's why it is difficult to include the commits history, I will close this one, and the new PR will be: https://github.com/OCA/l10n-germany/pull/31

**Pull request closed without merging**
