### PR TITLE
[14.0] [mig] l10n_de_steuernummer

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
No major Change. LGTM. Functional Tests.

**Comment by dsolanki-initos** [comment]
@tbaden can you please review this PR?

**Review by tbaden — APPROVED** [review]
code review: LGTM

**Comment by dsolanki-initos** [comment]
@pedrobaeza can you please merge this PR?

**Pull request merged**
