### PR TITLE
[14.0] [mig] l10n_de_country_states

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
Travis fails as the depended module PR is in the other repository "partner-contact" and its PR #1047 is left to merge.

**Comment by fshah-initos** [comment]
can someone please review this ticket?

**Review by dsolanki-initos — APPROVED** [review]
No major change

**Comment by fshah-initos** [comment]
@tbaden will you please review this PR?

**Review by tbaden — APPROVED** [review]
LGTM, did a code review

**Comment by fshah-initos** [comment]
@pedrobaeza Is it possible to merge this PR as it is approved.

**Comment by fshah-initos** [comment]
@pedrobaeza Will you please merge this PR as we got the approved label.
Thanks in advance!

**Comment by pedrobaeza** [comment]
/ocabot merge nobump

Please review in exchange 2/3 PRs of other contributors.

**Pull request merged**
