### PR TITLE
[11.0][IMP] l10n_de_tax_statement: add statement version 2019

### LINKED ISSUE #51: [12.0] Format issues with tax lines in l10n_de_tax_statement (v2019)
If i create a tax statement with values from 2019 and select "2019" in the field version i get a statement with line formats from the version 2018. 

This would be correct if we would create a tax statement for account moves from 2018, however some lines do not match the right format for 2019:

Line 51: instead of "EDITABLE_DISPLAY" -> "TOTAL_DISPLAY"
Line 52: instead of "EDITABLE_DISPLAY" -> "GROUP_DISPLAY"
Line 53: remove from "TOTAL_DISPLAY"
Line 54: instead of "GROUP_DISPLAY" -> "TAX_DISPLAY"
Line 60: remove from "TAX_DISPLAY" & add to "TOTAL_DISPLAY"
Line 62: remove from "TOTAL_DISPLAY"
Line 63: instead of "GROUP_DISPLAY" -> TAX_DISPLAY"

Bildschirmfoto 2019-08-19 um 10 25 16

I assume we also needs to have format settings for both versions ("2018" and "2019").

Furthermore as we now have "version" to create the report, we should change the follwoing string (line 65-67 in l10n_de_tax_statement.py):
    tax_total = fields.Monetary(
        compute='_compute_tax_total',
        string='Verbl. Ust.-Vorauszahlung (66 - 67)' 

to

    tax_total = fields.Monetary(
        compute='_compute_tax_total',
        string='Verbl. Ust.-Vorauszahlung' 

And finally due to latest source code changes the translations needs an update 
(i will do that for sure)

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/l10n-germany/issues/51 backported to V11

### CODE REVIEW

**Comment by astirpe** [comment]
@tv-openbig would you give it a try?

**Review by tv-openbig — APPROVED** [review]
@astirpe I have updated the module on a V11 instance and the version as well the formatting works well either for a tax declaration of 2018 invoices with the version configured as "2018" or for a tax declaration of 2019 invoices with the version configured as "2019". 👍 

Bildschirmfoto 2019-08-21 um 20 08 27

There is one string "Verbl. Ust.-Vorauszahlung (66-67)" i assume it is either in the source code or in the translations. The string should be "Verbl. Ust.-Vorauszahlung" (the final value at the bottom below the report tax lines holding the totals) in order to be independent from the version (year).

**Comment by astirpe** [comment]
@tv-openbig the string "Verbl. Ust.-Vorauszahlung (66-67)" is only present in the translations. I guess it can be directly fixed in the [OCA Weblate](https://translation.odoo-community.org/).

**Comment by astirpe** [comment]
It seems that the .pot file is not generated automatically in this repo `l10n-germany`. This is probably an impediment for the OCA Weblate to be aligned with the latest code. I'm going to open the PR to fix it.

**Comment by tv-openbig** [comment]
@astirpe I have recognized exactly that issue just at the same time.

Bildschirmfoto 2019-08-22 um 08 51 07

Do we have to generate new .pot file and de.po by hand ?
May we reuse the same .pot and de.po for both branches v11 / v12 ?

I can do that, if you want. 
At least i would complete your PR, if required.

**Comment by astirpe** [comment]
@tv-openbig PRs #54 and #55 should fix the issue. Once they are merged, the .pot file will be automatically generated for all the modules and the OCA Weblate automatically aligned with the latest code.

**Comment by tv-openbig** [comment]
@astirpe Ok, then i will wait for those merges in order to update the translations.

**Pull request merged**
