### PR TITLE
[12.0][mig]l10n_de_toponyms

### PR DESCRIPTION
**Pull request by hkapatel-initos**

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
Hello, @tbaden Can you please review this Pull and
Travis is failed https://app.travis-ci.com/github/OCA/l10n-germany/jobs/535743216#L322 it would be nice if you give a suggestion.

**Comment by tv-openbig** [comment]
@hkapatel-initos 
Theoretically it would work. However there is an issue with the installation, as here odoo standard v12 already imports german states (contacts module): https://github.com/odoo/odoo/blob/12.0/addons/l10n_de/data/res.country.state.csv
It was removed since V13: https://github.com/odoo/odoo/tree/13.0/addons/l10n_de/data. As a result the dependency to l10n_de_country_states caused an error on installation, because of duplicated states (cities and zips) entries in the database. The issue could be bypassed by manual removal of states in advance of the installation. However this will obviously leading to issues if l10n_de needs to be updated.

In general the functionality would work also on a V12 setup in the same way as on V13, V14:

Bildschirmfoto 2021-09-10 um 16 04 23
Bildschirmfoto 2021-09-10 um 16 03 56

**Comment by hkapatel-initos** [comment]
> @hkapatel-initos
> Theoretically it would work. However there is an issue with the installation, as here odoo standard v12 already imports german states (contacts module): https://github.com/odoo/odoo/blob/12.0/addons/l10n_de/data/res.country.state.csv
> It was removed since V13: https://github.com/odoo/odoo/tree/13.0/addons/l10n_de/data. As a result the dependency to l10n_de_country_states caused an error on installation, because of duplicated states (cities and zips) entries in the database. The issue could be bypassed by manual removal of states in advance of the installation. However this will obviously leading to issues if l10n_de needs to be updated.
> 
> In general the functionality would work also on a V12 setup in the same way as on V13, V14:
> 
> Bildschirmfoto 2021-09-10 um 16 04 23
> Bildschirmfoto 2021-09-10 um 16 03 56

I have done some changes and Travis is failed because of https://app.travis-ci.com/github/OCA/l10n-germany/jobs/536983793#L340.
can you please re-review it?

**Comment by tv-openbig** [comment]
> > @hkapatel-initos
> > Theoretically it would work. However there is an issue with the installation, as here odoo standard v12 already imports german states (contacts module): https://github.com/odoo/odoo/blob/12.0/addons/l10n_de/data/res.country.state.csv
> > It was removed since V13: https://github.com/odoo/odoo/tree/13.0/addons/l10n_de/data. As a result the dependency to l10n_de_country_states caused an error on installation, because of duplicated states (cities and zips) entries in the database. The issue could be bypassed by manual removal of states in advance of the installation. However this will obviously leading to issues if l10n_de needs to be updated.
> > In general the functionality would work also on a V12 setup in the same way as on V13, V14:
> > Bildschirmfoto 2021-09-10 um 16 04 23
> > Bildschirmfoto 2021-09-10 um 16 03 56
> 
> I have done some changes and Travis is failed because of https://app.travis-ci.com/github/OCA/l10n-germany/jobs/536983793#L340.
> can you please re-review it?

@hkapatel-initos I have deleted the last line which was highlighted as wrong in the check. How to apply the test once again ?

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig Travis issue is resolved and All checks are passed.

**Comment by tv-openbig** [comment]
> Hello, @tv-openbig Travis issue is resolved and All checks are passed.

Hello @hkapatel-initos Thanks a lot for your efforts! I will merge your PR.

**Pull request merged**
