### PR TITLE
[13.0][MIG] datev_export : Migration to version 13.0

### PR DESCRIPTION
**Pull request by carolinafernandez-tecnativa**
- Standard migration to v13

@Tecnativa

TT46193

@pedrobaeza

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
@fkantelberg @OSevangelist is it OK for you?

**Comment by fkantelberg** [comment]
LGTM

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
