### PR TITLE
[14.0][BACKPORT] datev export xml

### PR DESCRIPTION
**Pull request by fkantelberg**
Cherry-pick of the fixes done in the 15.0 PR.

### CODE REVIEW

**Comment by fkantelberg** [comment]
@tv-openbig @OSevangelist Just backports of fixes done in 15.0. Please also look on #151 to fix the CI on the 14.0 branch.

**Comment by tv-openbig** [comment]
@fkantelberg Do we need a new PR ? I have merged the PR #151 ...

**Comment by fkantelberg** [comment]
If you can't reopen it yes

**Comment by fkantelberg** [comment]
@tv-openbig See #152 let's hope the CI runs green now

**Pull request closed without merging**
