### PR TITLE
[13.0][mig]l10n_de_holidays

### PR DESCRIPTION
**Pull request by hkapatel-initos**
V12 PR: https://github.com/OCA/l10n-germany/pull/76
add oca_dependencies.txt on this module

### CODE REVIEW

**Comment by hkapatel-initos** [comment]
it would be nice if someone reviews here.

**Comment by tv-openbig** [comment]
@hkapatel-initos
I have checked the functionality. 
However i do not know if travis and runbot checks have to be successfull ?
Bildschirmfoto 2021-09-09 um 13 25 05
Bildschirmfoto 2021-09-09 um 13 23 03

**Comment by silverf0x0** [comment]
Hi All, what are we missing here? Any help needed?

**Comment by hkapatel-initos** [comment]
> Hi All, what are we missing here? Any help needed?

I mention the repo of the dependent modules in l10n_de_holidays/oca dependencies.txt but why Travis is not passed.

**Comment by hkapatel-initos** [comment]
Hello, @tv-openbig Travis is happy so.. it would be nice if could you merge this PR.

**Pull request merged**
